DATA_THERE SEGMENT 
    BCD DW 7000H;
    DATA_THERE ENDS

CODE_THAT SEGMENT
    ASSUME DS:DATA_THERE,CS:CODE_THAT
START:MOV AX,DATA_THERE
    MOV DS,AX
    MOV AX,0000H; 
    MOV CL,10;
    MOV BX,BCD
AGAIN:CMP [BX],0
    JNZ ZERO
    INC AL
    ZERO:JNC NIGGA
    INC AH
    JMP POSI
    NIGGA:INC DL
    POSI:INC BX
    LOOP AGAIN
    CMP DL,AL
    JC CARRY
    SUB DL,AL
    CARRY:HLT
    HLT
MOV AH,4CH;
INT 24H
CODE_THAT ENDS
END START
                   
           