DATA_THERE SEGMENT 
    ARRAY1 DW 7500H;
    ARRAY2 DW 7600H;
    ARRAY3 DW 7700H;
    ARRAY  DW 7800H;
    DATA_THERE ENDS

CODE_THAT SEGMENT
    ASSUME DS:DATA_THERE,CS:CODE_THAT
START:MOV AX,DATA_THERE
    MOV DS,AX
    MOV BX,ARRAY1
    MOV SI,ARRAY2
    MOV DI,ARRAY3
    MOV BP,ARRAY
    MOV CL,05;
AGAIN:MOV DH,[BX]
    ADD DH,DS:[SI]
    MOV DS:[DI],DH
    JNC SKIP
    MOV DS:[BP],01H;
    SKIP:INC BX
    INC SI
    INC DI
    INC BP
    LOOP AGAIN
    HLT
MOV AH,4CH;
INT 24H
CODE_THAT ENDS
END START
                   
           